/* generated by rust_qt_binding_generator */
use libc::{c_char, c_ushort, c_int};
use std::slice;
use std::char::decode_utf16;

use std::sync::Arc;
use std::sync::atomic::{AtomicPtr, Ordering};
use std::ptr::null;

use db::*;


pub enum QString {}

fn set_string_from_utf16(s: &mut String, str: *const c_ushort, len: c_int) {
    let utf16 = unsafe { slice::from_raw_parts(str, to_usize(len)) };
    let characters = decode_utf16(utf16.iter().cloned())
        .map(|r| r.unwrap());
    s.clear();
    s.extend(characters);
}



fn to_usize(n: c_int) -> usize {
    if n < 0 {
        panic!("Cannot cast {} to usize", n);
    }
    n as usize
}


fn to_c_int(n: usize) -> c_int {
    if n > c_int::max_value() as usize {
        panic!("Cannot cast {} to c_int", n);
    }
    n as c_int
}


pub struct DatabaseQObject {}

pub struct DatabaseEmitter {
    qobject: Arc<AtomicPtr<DatabaseQObject>>,
    path_changed: fn(*mut DatabaseQObject),
}

unsafe impl Send for DatabaseEmitter {}

impl DatabaseEmitter {
    /// Clone the emitter
    ///
    /// The emitter can only be cloned when it is mutable. The emitter calls
    /// into C++ code which may call into Rust again. If emmitting is possible
    /// from immutable structures, that might lead to access to a mutable
    /// reference. That is undefined behaviour and forbidden.
    pub fn clone(&mut self) -> DatabaseEmitter {
        DatabaseEmitter {
            qobject: self.qobject.clone(),
            path_changed: self.path_changed,
        }
    }
    fn clear(&self) {
        let n: *const DatabaseQObject = null();
        self.qobject.store(n as *mut DatabaseQObject, Ordering::SeqCst);
    }
    pub fn path_changed(&mut self) {
        let ptr = self.qobject.load(Ordering::SeqCst);
        if !ptr.is_null() {
            (self.path_changed)(ptr);
        }
    }
}

pub trait DatabaseTrait {
    fn new(emit: DatabaseEmitter) -> Self;
    fn emit(&mut self) -> &mut DatabaseEmitter;
    fn path(&self) -> &str;
    fn set_path(&mut self, value: String);
    fn add_value(&mut self, key: String, value: String) -> ();
    fn get_value(&self, key: String) -> String;
}

#[no_mangle]
pub extern "C" fn database_new(
    database: *mut DatabaseQObject,
    database_path_changed: fn(*mut DatabaseQObject),
) -> *mut Database {
    let database_emit = DatabaseEmitter {
        qobject: Arc::new(AtomicPtr::new(database)),
        path_changed: database_path_changed,
    };
    let d_database = Database::new(database_emit);
    Box::into_raw(Box::new(d_database))
}

#[no_mangle]
pub unsafe extern "C" fn database_free(ptr: *mut Database) {
    Box::from_raw(ptr).emit().clear();
}

#[no_mangle]
pub unsafe extern "C" fn database_path_get(
    ptr: *const Database,
    p: *mut QString,
    set: fn(*mut QString, *const c_char, c_int),
) {
    let o = &*ptr;
    let v = o.path();
    let s: *const c_char = v.as_ptr() as *const c_char;
    set(p, s, to_c_int(v.len()));
}

#[no_mangle]
pub unsafe extern "C" fn database_path_set(ptr: *mut Database, v: *const c_ushort, len: c_int) {
    let o = &mut *ptr;
    let mut s = String::new();
    set_string_from_utf16(&mut s, v, len);
    o.set_path(s);
}

#[no_mangle]
pub unsafe extern "C" fn database_add_value(ptr: *mut Database, key_str: *const c_ushort, key_len: c_int, value_str: *const c_ushort, value_len: c_int) {
    let mut key = String::new();
    set_string_from_utf16(&mut key, key_str, key_len);
    let mut value = String::new();
    set_string_from_utf16(&mut value, value_str, value_len);
    let o = &mut *ptr;
    o.add_value(key, value)
}

#[no_mangle]
pub unsafe extern "C" fn database_get_value(ptr: *const Database, key_str: *const c_ushort, key_len: c_int, d: *mut QString, set: fn(*mut QString, str: *const c_char, len: c_int)) {
    let mut key = String::new();
    set_string_from_utf16(&mut key, key_str, key_len);
    let o = &*ptr;
    let r = o.get_value(key);
    let s: *const c_char = r.as_ptr() as *const c_char;
    set(d, s, r.len() as i32);
}
