/* generated by rust_qt_binding_generator */
#ifndef BINDINGS_H
#define BINDINGS_H

#include <QtCore/QObject>
#include <QtCore/QAbstractItemModel>

class Database;

class Database : public QObject
{
    Q_OBJECT
public:
    class Private;
private:
    Private * m_d;
    bool m_ownsPrivate;
    Q_PROPERTY(QString message READ message NOTIFY messageChanged FINAL)
    Q_PROPERTY(QString path READ path WRITE setPath NOTIFY pathChanged FINAL)
    explicit Database(bool owned, QObject *parent);
public:
    explicit Database(QObject *parent = nullptr);
    ~Database();
    QString message() const;
    QString path() const;
    void setPath(const QString& v);
Q_SIGNALS:
    void messageChanged();
    void pathChanged();
};
#endif // BINDINGS_H
