/* generated by rust_qt_binding_generator */
#ifndef ROCKSDB_H
#define ROCKSDB_H

#include <QtCore/QObject>
#include <QtCore/QAbstractItemModel>

class Database;

class Database : public QObject
{
    Q_OBJECT
public:
    class Private;
private:
    Private * m_d;
    bool m_ownsPrivate;
    Q_PROPERTY(QString path READ path WRITE setPath NOTIFY pathChanged FINAL)
    explicit Database(bool owned, QObject *parent);
public:
    explicit Database(QObject *parent = nullptr);
    ~Database();
    QString path() const;
    void setPath(const QString& v);
    Q_INVOKABLE void addValue(const QString& key, const QString& value);
    Q_INVOKABLE QString getValue(const QString& key) const;
Q_SIGNALS:
    void pathChanged();
};
#endif // ROCKSDB_H
